name: oOf dynamic again

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://android.googleapis.com/packages/ota-api/vsmart_jacaranda_jacarandaopen/12198da2140b32aa979058845de3c41f4be9e730.zip
  ROM_NAME: paa
  ZIP_NAME: paa
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget 
            sudo -E apt-get install expect
            sudo apt-get install p7zip-full
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install -y brotli
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar
            sudo apt install software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt update
            sudo apt install python3.8
       - name: System.img
         run: |
              sudo aria2c $ROM_URL
        
       - name: System.img
         run: |
              sudo aria2c https://index.download-content.cf/sdat2img.py
              sudo chmod +x sdat2img.py
              sudo unzip *.zip
              sudo brotli -d system.new.dat.br
              sudo rm -f system.new.dat.br
              sudo ./sdat2img.py system.transfer.list system.new.dat system.img
              sudo rm -rf system.new.dat system.transfer.list
              sudo brotli -d product.new.dat.br
              sudo rm -f product.new.dat.br
              sudo ./sdat2img.py product.transfer.list product.new.dat product.img
              sudo rm -rf product.new.dat product.transfer.list
              
       - name: upload aonly n info
         run: |
              sudo su
              dd if=/dev/zero of=system_new.img bs=6k count=1048576
              mkfs.ext4 system_new.img
              tune2fs -c0 -i0 system_new.img
              mkdir system
              mkdir system_new
              sudo mount -o loop system_new.img system_new/
              sudo mount -o ro system.img system/
              sudo cp -v -r -p system/* system_new/
              sync
              sudo umount system/
              cd system_new
              sudo rmdir product
              cd ..
              mkdir systemop7
              sudo mount -ro loop system.img systemop7/
              sudo cp -v -r -p systemop7/product system_new/
              sudo umount systemop7/
              cd system_new/system
              sudo rm product
              sudo mkdir product
              cd ..
              cd ..
              mkdir product
              sudo mount -o ro product.img product/
              sudo cp -v -r -p product/* system_new/system/product/
              sync
              sudo umount product/
              sudo umount system_new/
              sudo rm -rf system system.img product.img
              ls
              mv system_new.img system.img
              sudo zip -r Windows10-64.zip system.img

       - name: upload aonly n info
         run: |
              expect -c "
              spawn sftp ruiii@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"
              send \"${{ secrets.PASSWORD }}\r\"
              expect \"sftp> \"
              send \"cd /home/pfs/project/rui-ports/dumps\r\"
              set timeout -1
              send \"put Windows10-64.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
