name: oOf dynamic again

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://oxygenos.oneplus.net/OnePlus7TProOxygen_13.W.06_OTA_006_all_2007030104_71b23c0ee98240df.zip
  ROM_NAME: OxygenOS
  ZIP_NAME: OxygenOS
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing environments
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo apt-get install wget
            sudo apt-get install p7zip-full
            sudo apt-get update -y
            sudo apt-get install -y simg2img  
            sudo apt-get install -y brotli
            sudo apt-get install unzip
            sudo apt-get install zip gzip tar
            sudo apt install software-properties-common
            sudo add-apt-repository ppa:deadsnakes/ppa
            sudo apt update
            sudo apt install python3.8

       - name: System.img
         run: |
              sudo aria2c http://bigota.d.miui.com/20.7.30/miui_LMI_20.7.30_2de74df6ca_11.0.zip
        
       - name: System.img
         run: |
              sudo aria2c http://tdrive.manofuranium.workers.dev/sdat2img.py
              sudo chmod +x sdat2img.py
              sudo unzip *.zip
              sudo brotli -d system.new.dat.br
              sudo rm -f system.new.dat.br
              sudo ./sdat2img.py system.transfer.list system.new.dat system.img
              sudo rm -rf system.new.dat system.transfer.list
              sudo brotli -d product.new.dat.br
              sudo rm -f product.new.dat.br
              sudo ./sdat2img.py product.transfer.list product.new.dat product.img
              sudo rm -rf product.new.dat product.transfer.list
              sudo zip miuia11.zip system.img product.img
              
       - name: upload aonly n info
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer bit miuia11.zip
 
